server/engine/engine.py
Minor path issues found along the way. This assumes you run the tools from the IK/ID folders, which I expect is the intended behavior given the path to the marker data.
=> Model path setup files

server/engine/engine.py, server/engine/requirements.txt
This PR includes updates to support `nimblephysics` 0.8.80, including the new flags for setting GRF shifting (`shiftGRFs`) and setting the max number of trials used to solve for model mass during the dynamics fitting step (`maxTrialsToSolveMassOver`).
=> Updates for nimblephysics 0.8.80

server/app/mocap_server.py, server/engine/engine.py
We were getting exceptions when PubSub hits a rate limiter, if we try to send messages that are too large, and then (because we didn't have a try-catch around the PubSub interactions) that would crash the app and subsequently the whole process.
=> Adding catches around PubSub interactions

frontend/src/pages/search/SearchView.tsx
More information of solved issues in #40:
- In search remove text that says "Placeholder" => Now it shows "Your keywords..." (Should we change it to something else?)
- When you search and hit "return" it doesn't give you your results (looks like the full data) => Removed default behaviour when pressing enter since it automatically updates when you finishes typing.
=> Removed default enter press. Changed input placeholder.

frontend/src/pages/mocap/MocapSubjectView.tsx
This addresses https://github.com/keenon/AddBiomechanics/issues/63, by adding UI for setting a static trial under the "Advanced" tab. We don't yet have a way to set the neutral pose for your skeleton, or set markers to ignore, but it's a start.
=> Adding static trial upload in the advanced options tab

frontend/src/pages/files/FileControlsWrapper.tsx, frontend/src/state/MocapS3Cursor.ts
Here's my take on the "display which public folder you're a subfolder of" feature.
One (somewhat questionable) design decision I mode in here that we can+should discuss: if you make a folder public, and later make a folder _containing_ that folder public, currently we prioritize the parent folder, and basically hide the fact that the sub-folder was ever public (you can no longer edit the attributes of the dataset). I don't know how I feel about this. What do you think?
=> Subfolder controls display

frontend/src/pages/files/FileControlsWrapper.tsx, frontend/src/pages/search/SearchResult.tsx, frontend/src/state/MocapS3Cursor.ts
User's inserted title for a dataset was not visible anywhere, so I added it to other person's public datasets (if exists). It is also shown in the search results.
Regarding description in search results, there was a little bug causing it to not be shown (the function that filters the urls expect it to not to have a "/" at the end, and in this case, it was having it).
**Note:** Right now, we are only searching by folder's name, but it would be interesting allowing searching in the description and user's inserted title too. However, I think this would imply loading all `_search.json` files beforehand. Also, we cannot search "Home Folder" datasets, since the folder name is empty string ("").
=> Added user's inserted title to dataset view and search results. Added dataset description to search results.

frontend/src/components/TagEditor.tsx
I detected that, if a header is selectable, and you select it, it is removed from the list of options, but the children are still in the list. This is confusing and an error, because visually the children of a selected header appear as either children of the previous element, or as siblings of the previous element.
I added redundant headers to avoid this behavior.
=> Added redundant headers to avoid disappearance of selectable headers.

server/engine/engine.py
This PR addresses two issues:
- #65: Adds a call to the new `MarkerFitter::writeCSVData` to create a `plot.csv` file, which is needed for front-end plotting.
- #96: Skips the call to `OpenSimParser::replaceOsimInertia` when not fitting dynamics.
These changes depend on the associated `nimblephysics` PR: https://github.com/keenon/nimblephysics/pull/165.
=> Adding call to `MarkerFitter::writeCSVData` for front-end plotting

frontend/src/pages/mocap/MocapTrialModal.tsx
When the scales definitions are created, there was no final else case, so a scale was not created for elements that don't meet the criteria of the rest of the cases.
=> Added missing else case to 3d visualizer

server/app/mocap_server.py, server/engine/.gitignore, server/engine/engine.py, server/engine/exceptions.py, server/engine/testing.py
This PR implements some basic error reporting features to the framework in `engine.py`:
1. `Engine` is now subclassed to a metaclass `ExceptionHandlingMeta` which automatically wraps all methods of `Engine` with a try-except block (except the `__init__` method).
2. In the except branch, a new exception will be raised that will provide some generic error messaging depending on the stage of the pipeline that the exception occurred in. 
3. This new exception will also pipe through the original error message that can be printed alongside the generic message.
4. All information is printed to a file called `_errors.json`. If no errors occur, an empty `_errors.json` is printed.
A few other things:
- I've added a basic test to `testing.py` that we can expand upon if needed.
- All `exit(1)` calls …
=> Support for error reporting in `engine.py`

frontend/src/pages/mocap/MocapSubjectView.tsx
This PR allows the frontend to turn on the new backend feature which can automatically run and/or export a Moco Inverse problem for you.
=> Adding runMoco and exportMoco checkboxes to the advanced tab

server/app/mocap_server.py
Sherlock will fail to queue our jobs with sbatch if we're too greedy, and in the current version there's no error checking and retrying, and also no rate limiting, which has been making me nervous. This is a PR to hopefully make us more robust to having hundreds of subjects uploaded at once, and not accidentally drop a bunch on the floor.
=> Adding logic to respect Sherlock resource limits

server/engine/engine.py, server/engine/templates/template_moco.m
This PR adds `template_moco.m`, which prints out a `MocoInverse` script to using in Matlab (similar to `template_moco.py`). The necessary changes to `engine.py` are included as well.
=> Print out `MocoInverse` script for Matlab

server/Dockerfile.harvester_dev, server/Dockerfile.harvester_prod, server/app/data_harvester.py, server/app/mocap_server.py, server/app/reactive_s3/reactive_s3_index.py, server/slurm_persistent_harvester_job_dev.sh, server/slurm_persistent_harvester_job_prod.sh, server/slurm_persistent_job_dev.sh, server/slurm_persistent_job_prod.sh, test_harvester.sh
... instead of taking them as args.
This PR also:
- Fixes a bug with the PubSub system
- Prioritizes the processing of subjects in the "real data" section of S3, and only when that's all done does it add subjects from the "standardized" section
- adds a `DYNAMICS` tag file to subjects who are processed successfully and have dynamics results, to make it easy to filter subjects without downloading everything.
=> The harvester now reads the standard skeletons from S3

server/engine/engine.py, server/engine/helpers.py, server/engine/requirements.txt, server/engine/testing.py
This PR adds a step to `run_moco` that will update the `plot.csv` with the MocoSolution contents. This will allow us to plot muscle excitations and activations in the front-end plotter.
=> Update `plot.csv` with MocoInverse solution

server/data/Rajagopal2015/raw/_subject.json, server/engine/engine.py, server/engine/testing.py
This PR updates the data trimming logic to support trimming based on user-provided time ranges. The time ranges can be specified for each trial individually by providing a dictionary in `subjectJson` whose keys are the trial names and the values are a two-element arrays specifying the initial and final times. 
We still always check to see if the time range between the markers and ground reaction forces are consistent. If not, we trim the markers and forces to the intersection of both time ranges. The remaining trimming logic, if enabled, comes after that.
We also now issue warnings if the either 1) we had to trim the markers/GRFs to be consistent or 2) if trial trimming/segmentation was not enabled, but probably should be.
=> Support data trimming to user-provided time ranges

frontend/src/pages/mocap/MocapSubjectView.tsx, frontend/src/state/MocapS3Cursor.ts
I have implemented a first version of "dismiss warnings".
Right now, you can check warnings to hide them. If you want to see dismissed warnings, there is a "show all warnings" checkbox at bottom of the warnings section.
**Questions:**
- Right now, everything is temporarily stored as states in react. How do we want to store user selections? I've been thinking and we have three options:
- 1. **Do nothing** and always show every warning when the user enters inside of a subject. This may be annoying, since you will have to dismiss them every time, and users would end up not dismissing them.
- 2. **Store dismissed warnings inside of a json file**. Which implies having to read the file every time someone enters the subject. Further, if someone who is not the owner enters, won't see dismissed …
=> Implemented dismiss and show all warnings.

server/data/Rajagopal2015/raw/_subject.json, server/engine/engine.py
- Added the final time ranges for each trial in all `_result.json` folders.
- The boolean flag `self.segmentTrials` has been updated to `self.segmentedTrials`, which is a list of trial names to be segemented.
Tested locally.
=> Add trial time ranges to `_result.json` files to support frond-end display

frontend/src/pages/auth/ForgotPassword.tsx
This should solve the password recovery bug (#217).
The problem was that the link to the confirmation page was not correct.
=> Solved password recovery not working.

server/engine/src/exceptions.py, server/engine/src/subject.py
Fixes #221 
As the title suggests, this PR reimplements the automated exception handling from the old `Engine` class. Since the new `Subject` class mostly mimics the old `Engine` class, I've moved the exception handling stuff there.
There is one minor change from the original implementation to note. Since some of the methods within `Subject` are essentially helper methods called by other methods, I've added the new `EXCEPTION_MAP`: only the methods in this map are wrapped with the exception handling logic. These methods should only be the "top-level" methods called by `engine.py`. Otherwise, an `Error` will be raised by every helper method in the stack trace and the original exception message from `nimblephysics` will get buried.
As before, the error messages will get stored in a file …
=> Reconnect automated exception handling and error message system in backend

frontend/src/pages/data/SubjectView.tsx
Solves #279 
- New subjects do not have citation anymore. It is only at dataset level.
- Citations inserted in previous versions appear as non-editable, with a message indicating:
- We are replacing citations for individual subjects with dataset citations. Please add a citation for the full dataset and remove the subject citations.
- It is possible to remove old deprecated citations with a new button that only appears if the citation is present.
=> Subject citation deprecated

frontend/src/components/DropFile.tsx, frontend/src/model/UserProfile.ts, frontend/src/pages/profile/ProfileView.tsx
First check if file is an image. Then convert into canvas and finally convert into png, so we always use the same format internally.
Fixed error of file chooser invoked twice when selecting profile picture in chromium-based browsers.
=> Restructured dropProfilePicture function, so it accepts more image formats

server/engine/src/dynamics_pass/missing_grf_detection.py
This is a small update to the server, to respect the manual GRF annotations in the new pipeline.
=> Use the manual GRF labels in the new pipeline, if they are available

frontend/src/model/LiveDirectory.ts, frontend/src/model/SubjectViewState.ts, frontend/src/pages/data/SubjectView.tsx
This is a few small fixes to the frontend. Trials had a few child files that weren't being deleted when you tried to delete a trial on the web GUI, which was then causing that trial to stick around.
Six tried to process a subject despite not being able to delete a trial that didn't have markers, but that failed to get picked up by the server, which doesn't allow processing when there are missing trial marker data, so I added a frontend check and an explanation to prevent that behavior.
=> Fixing a bug Six ran into where trials would not delete, and empty trials blocked processing

server/engine/src/kinematics_pass/subject.py, server/engine/tests/data/.gitignore, server/engine/tests/data/rajagopal2015_no_data_original/_subject.json, server/engine/tests/data/rajagopal2015_no_data_original/unscaled_generic.osim, server/engine/tests/test_subject.py
Partially addresses #323 (backend only).
Currently, the backend will procedure forward to kinematics fitting even if the uploaded subject has no motion data (.trc or .c3d file) associated with it. This PR addresses this issue on the backend and adds some accompanying tests.
Exceptions are now raised if:
1. The `trials` folder is missing.
2. No trial subfolders exist under the `trials` folder.
3. No motion data exists in any of the trial subfolders.
=> Throw exceptions for missing subject data

server/app/src/mocap_server.py
=> Include `data.csv` file when downloading trial segment files from the S3 bucket

server/engine/src/moco_pass/moco_pass.py
Fixes #367.
This prevents failures during processing on Sherlock where the available CPU threads exceeds the number of time points in the provided kinematic data.
=> Limit the number of threads during path fitting in the Moco pass

static/download_data.html, static/faq.html, static/index.html
These changes include:
- Removes the "New!" red text on the View Public Data button.
- Removes the "Beta" red text on the dataset download page.
- Updates the FAQ page to improve wording for Moco support and update citations.
=> Various improvements to the static page
