keenon/AddBiomechanics

- frontend/src/index.tsx
- frontend/src/layouts/Navbar.tsx
- frontend/src/pages/profile/ProfileView.tsx
Added an editable profile page.
> Profile page

- frontend/src/pages/profile/ProfileView.tsx
Fix wrong placeholder for contact input.
> Fixed wrong text placeholder in contact input.

- frontend/src/pages/profile/ProfileView.tsx
Now a user can see other users' profiles.
> Viewing other users' profiles.

- .gitignore
- server/engine/engine.py
@keenon I'm only requesting a review since our conversations implied that this shouldn't be necessary. But if this fix seems reasonable let me know.
> Update body masses after marker fitting step

- server/app/mocap_server.py
Re https://github.com/keenon/AddBiomechanics/issues/34.
This needs to wait to merge in until after AWS has approved the addbiomechanics.org domain as one we can send emails from, so don't merge this for the next 24 hours at least.
> Updating completed processing email text

- frontend/src/pages/auth/Login.tsx
- frontend/src/pages/files/FileControlsWrapper.tsx
- frontend/src/pages/mocap/MocapSubjectView.tsx
- frontend/src/pages/profile/ProfileView.tsx
- frontend/src/pages/search/SearchView.tsx
- frontend/src/state/MocapS3Cursor.ts
- frontend/src/state/ReactiveS3.ts
- frontend/src/utils.ts
- frontend/yarn.lock
This PR fixes a bunch of random bugs:
- There was a bunch of view code that was making web requests on every re-render, which was spamming our AWS servers and leading to higher bills as well as rendering bugs.
- Text files like server logs and OpenSim XML were failing to download because they were downloading from an incorrect path (the prefix "protected/<region>:<username>" was getting prepended twice)
- Login flow was redirecting in a loop
> A bunch of misc bug fixes

- server/engine/engine.py
This PR adds support for the recent nimblephysics addition to include a static marker trial to include static joint angles as a prior in the `MarkerFitter` problem. I've currently implemented this so that if users specify a trial name "static", it will get detected for the static trial and the remaining trials will be processed normally. 
This PR also adds support for the `ignoreFootNotOverForcePlate` flag.
> Add support for including static trials + ignore foot over force plate flag

- frontend/src/components/ProfileDropdown.tsx
- frontend/src/index.tsx
- frontend/src/pages/files/FileControlsWrapper.tsx
- frontend/src/pages/mocap/MocapSubjectView.tsx
- frontend/src/pages/profile/ProfileView.tsx
- frontend/src/state/MocapS3Cursor.ts
- frontend/src/state/ReactiveS3.ts
Still having the problem of not being able to type user's information without it hanging for half of a second between characters.
For testing purposes, I added the new default profile image as a link from wikimedia commons. We should download it and locate somewhere we have control over.
> Fixing profile page inputs

- frontend/src/layouts/Footer.tsx
- frontend/src/layouts/Horizontal.tsx
Small change to footer so it does not cover elements and has a bg color consistent with the application.
> Fixed footer covering elements. Added color to footer.

- server/app/mocap_server.py
This sets a maximum number of lines (20) that can be merged to be sent as a single message over MQTT. The objective here is to stay well under the "message maximum size limit". It seems if we go over the message maximum size, the MQTT PubSub socket just quietly closes, and all subsequent calls to PubSub crash, and then that crashes the server :/
So hopefully this helps prevent that.
> Max size for log batching

- frontend/src/index.tsx
- frontend/src/utils.ts
Now the toast notification is not closed on click (you can close it by swiping or clicking the x), and you can insert links on it. I added also a parameter to control automatic close time.
> Toast notification on login formatted.

- frontend/src/components/ProfileDropdown.tsx
- frontend/src/layouts/Navbar.tsx
Related to #41.
I have added links in the menus to Help, Terms of Service and Forums.
> Added help, tos and forum links.

- server/engine/engine.py
- server/engine/plotting.py
Addresses issues: #49, #79, #80 
- Fixed results plotting error where marker error time range was incorrectly scaled.
- Fixed incorrect plot labels for GRFs and IK and ID results.
- Added a description of the output model `final.osim` to the README.
- Added a breakdown of the changes in the model total and body segment masses to the README.
> Report body mass changes, fix plot labels, and add description for `final.osim`

- frontend/src/pages/files/FileControlsWrapper.scss
- frontend/src/pages/files/FileControlsWrapper.tsx
Citation and funding were not shown in other people's folders. This should fix it.
> Showing citation and funding.

- frontend/src/components/DropFile.tsx
- frontend/src/state/ReactiveS3.ts
- frontend/src/state/RobustHandler.ts
- frontend/src/state/RobustUpload.ts
This PR fixes the upload progress bars, so that they should actually show progress of the uploads now.
> Fixing the upload progress bars

- server/engine/engine.py
- server/engine/helpers.py
- server/engine/testing.py
This PR updates the trial trimming/segmentation code to also handle trial segments with no marker information.
I also added a test based on a new helper function that reconciles marker segments and non-zero force segments.
> Automatically trim/segment trials based on timestamps with no marker information

- server/engine/engine.py
- server/engine/testing.py
This makes sure we correctly handle exceptions from the new `NIMBLE_THROW` and `NIMBLE_THROW_IF` macros in `nimblephysics`.
> Add test to confirm that C++ `std::runtime_error` are handled correctly

- server/engine/engine.py
- server/engine/requirements.txt
Also fixing a divide by 0 in the results
> Bumping to v0.9.9, fixing new writeSubjectOnDisk() API

- frontend/src/pages/mocap/MocapSubjectView.tsx
- frontend/src/state/MocapS3Cursor.ts
- frontend/src/utils.tsx
Retrieving (and caching) `_errors.json` file and showing the error in the frontend.
> Error reporting in frontend

- frontend/src/state/MocapS3Cursor.ts
- server/app/mocap_server.py
- server/engine/engine.py
Frontend now only reports errors on the ERROR flag, backend now correctly pushes it on errors
> Fixing error handshake

- server/engine/helpers.py
- server/engine/templates/template_moco.py
This PR updates the MocoInverse problem settings in an attempt to get more consisent solutions on the Linux builds.
> Update MocoInverse settings

- server/data/Rajagopal2015/raw/Rajagopal2015_CustomMarkerSet.osim
- server/engine/engine.py
Self-explanatory.
I'm also using this PR as an excuse to update the Rajagopal2015 example.
> Remove `RuntimeError` when no "sex" field

- server/app/data_harvester.py
- server/app/reactive_s3/reactive_s3_index.py
- test_harvester.sh
The idea here is to have a daemon that can scan for new uploaded subjects, convert them to a standardized OpenSim model, and re-upload them to a specific location in S3 to be processed.
The hope is to:
(1) Save subjects that are uploaded to process, and then deleted by the user
(2) Automatically aggregate large datasets of motion processed in several standard skeletons
> First version of a data harvesting daemon

- frontend/src/pages/mocap/MocapSubjectView.tsx
Implemented frontend for trimming. It is not connected to the backend yet, so states and values do nothing for now.
> Implemented frontend for trimming (no connected to backend yet).

- server/app/src/mocap_server.py
Fixes #204 
Current implementation allocates 4GB of RAM for every 25MB of uploaded subject data, and allocates 1 CPU per 4GB of RAM (thus preserving the RAM-to-CPU ratio we already had). Not sure if the current allocation logic makes sense, but it can be easily adjusted.
> Allocate Sherlock resources based on total size of subject data

- server/app/src/mocap_server.py
> Fix logic for detecting Sherlock allocation needs

- frontend/src/pages/data/DatasetView.tsx
Solves https://github.com/keenon/AddBiomechanics/issues/216, so users consider their folders as datasets and feel more inclined to organize subjects
> Changed folder nameto dataset in DatasetView

- frontend/src/model/Session.ts
- frontend/src/model/UserHomeDirectory.ts
- frontend/src/model/UserProfile.ts
- frontend/src/pages/data/DatasetView.tsx
- frontend/src/pages/data/SubjectView.tsx
Also, dataset and citation info are now more aesthetic in read only mode.
Inherit info for dataset folders.
Fixed some warnings.
Badges in subjectview status.
> WIP - Restructured dataset view so buttons and attribution are at left panel

- frontend/package.json
- frontend/src/components/DropFile.tsx
- frontend/src/pages/data/SubjectView.tsx
- frontend/yarn.lock
> Allowing selection of files to upload (not only drop) and showing filename

- frontend/package.json
- frontend/src/components/DropFile.tsx
- frontend/src/pages/data/DatasetView.tsx
- frontend/yarn.lock
> Added time to date. Removed add subject from home.

- frontend/src/pages/data/SubjectView.tsx
- frontend/src/pages/profile/ProfileView.tsx
- frontend/src/utils.tsx
- frontend/src/v1/index_old.tsx
- frontend/src/v1/pages/profile/ProfileView.tsx
If the processing flag or the slurm flag exist for more than 6 hours, tell the user to reprocess.
@nickbianco I am not sure how should we procced with the "Waiting for server" status (#248), since there are no flags or files that I know of that we can check for times. In the code, it is in "Waiting for server" status only if there are no other flags, like the processing, queued, error or results flags present.
Should we create a new flag for that case?
> Notifying processing. If not finished in 6 hours, ask to reprocess.

- server/app/src/data_harvester.py
It turns out our data harvester logs are full of attempting to copy the same subject over and over again, and then crashing with a segfault. Here's a representative snippet:
```^[[1;33mWarning [LocalResource.cpp:48]^[[0m [LocalResource::constructor] Failed opening file '/tmp/tmpu1bq7e4i/Geometry/Rib1R.vtp.ply' for reading: No such file or directory
^[[1;33mWarning [CompositeResourceRetriever.cpp:96]^[[0m [CompositeResourceRetriever::retrieve] All ResourceRetrievers registered for this schema failed to retrieve the URI 'file:///tmp/tmpu1bq7e4i/Geometry/Rib1R.vtp.ply' (tried 1).
^[[1;33mWarning [MeshShape.cpp:493]^[[0m [MeshShape::loadMesh] Failed loading mesh 'file:///tmp/tmpu1bq7e4i/Geometry/Rib1R.vtp.ply' with ASSIMP error 'Unable to open file …
```
> Moving copy_snapshots() call in a separate process to protect against segfaults

- frontend/src/model/SubjectViewState.ts
- frontend/src/pages/data/SubjectView.tsx
Added a new button to show/hide reviewed warnings. Its state is saved in the subject json file.
> Warnings can now be marked or unmarked as review individually

- server/emailtest.py
Changed link to your data in the email, as well as the last line as suggested in #280.
> Changed email link and text.

- frontend/src/components/DropFile.tsx
- frontend/src/components/ProfileDropdown.tsx
- frontend/src/model/Session.ts
- frontend/src/model/UserProfile.ts
- frontend/src/pages/data/DataTypeRouter.tsx
- frontend/src/pages/layouts/Horizontal.tsx
- frontend/src/pages/layouts/Topbar.tsx
- frontend/src/pages/profile/ProfileRouter.tsx
- frontend/src/pages/profile/ProfileView.tsx
Added profile pictures to user profile pages.
> Added profile pictures.

- cli/addbiomechanics/addb.py
- cli/addbiomechanics/commands/download_files.py
- cli/addbiomechanics/commands/view_energy.py
- frontend/src/pages/data/SubjectView.tsx
- server/engine/src/kinematics_pass/subject.py
This was responsible for some of the ASB demos, and I'd like to get it back so that we can use it for exoskeleton analysis.
> WIP: Reviving the "addb view-energy" command

- server/engine/src/dynamics_pass/dynamics_pass.py
Reduces dynamics fitting threshold from 50 frames of valid GRF data to 5 frames.
> Reduce dynamics fitting threshold

- server/docker_base/Dockerfile
- server/docker_base/rebuild.sh
- server/engine/src/writers/opensim_writer.py
I had issues rebuilding the base Docker container when compiling OpenSim. These changes, upgrading to Ubuntu 22.04 and changing some CMake commands, seem to resolve all issues.
I've also included updates to `opensim_writer.py` so that written files use the original time range from the uploaded data. Changing the time range led to a downstream bug when solving the Moco problem.
These changes are included in the container that is currently live on `dev`.
> Updates to the base Dockerfile + OpenSim writer updates

- frontend/src/model/UserHomeDirectory.ts
- frontend/src/pages/data/DatasetView.tsx
> Fixing frontend issues

- frontend/src/pages/data/SubjectView.tsx
> Add links to forum and GitHub when error happens

- server/engine/src/engine.py
- server/engine/src/kinematics_pass/trial.py
- server/engine/tests/test_subject.py
Temporarily patches issue #358.
> Disable the `Subject` method `clean_marker_traces`

- frontend/src/components/TagEditor.tsx
- frontend/src/pages/data/SubjectView.tsx
- Fixes #355.
- Fixes #356.
- Fixes #354.
- Partially Fixes #315.
> Fixes to frontend related to rehabweek epic issue

- static/css/custom.css
- static/data_sharing_mission.html
- static/download_data.html
- static/faq.html
- static/index.html
- static/tips_and_tricks.html
- static/tos.html
> Update the static page: dataset download options and forum nav-item

- server/engine/src/kinematics_pass/subject.py
Use the model filename that matches the model filename for the OpenCap skeleton in the PresetSkeletons folder.
> Use correct model file name for OpenCap model
